{
    "apiVersion": "radix.equinor.com/v1",
    "kind": "RadixApplication",
    "metadata": { "name": "sapAPI" },
    "spec": {
        "environments": [
           { "name": "dev", "build": { "from": "master" } }
        ],
        "components": [
            {
                "name": "main",
                "secrets": CLIENT_SECRET,
                "src": ".",
                "public": "true",
                "publicPort": "http",
                "ports": [
                     { "name": "http", "port": 5000 }
                ],
                "environmentConfig": [
                    "environment": "dev", "variables": 
                        { "CLIENT_ID": "a20b05b6-bedc-4006-9fbd-74d5c5a85882",
                          "API_BASE": "https://login.microsoftonline.com/",
                          "REDIRECT_URI": "http://localhost:5000/getAToken",
                          "TENANT_ID": "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
                        }
                ],
            }
        ]
    }
}